apiVersion: v1
kind: Service
metadata:
  name: gora
  labels:
    app: quarks-gora
spec:
  ports:
  - port: 8443
    name: ssl
  clusterIP: None
  selector:
    app: quarks-gora
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quarks-gora
spec:
  selector:
    matchLabels:
      app: quarks-gora
  serviceName: "gora"
  template:
    metadata:
      labels:
        app: quarks-gora
      annotations:
        quarks.cloudfoundry.org/restart-on-update: "true"
    spec:
      containers:
      - name: gora
        image: ghcr.io/cfcontainerizationbot/quarks-gora:latest
        imagePullPolicy: Never
        command:
        - /usr/local/bin/quarks-gora
        volumeMounts:
        - name: cert
          readOnly: true
          mountPath: "/etc/gora"
        env:
        - name: SSL
          value: "true"
        - name: PORT
          value: "443"
        - name: SERVER_CRT
          value: "/etc/gora/certificate"
        - name: SERVER_KEY
          value: "/etc/gora/key"
        - name: KEYDATA
          valueFrom:
            secretKeyRef:
              name: gora-cert
              key: private_key
      volumes:
      - name: cert
        secret:
          secretName: gora-cert
          items:
          - key: private_key
            path: key
          - key: certificate
            path: certificate
