name: Github Pages
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'cloudfoundry-incubator/quarks-docs'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build 🔧
      run: |
           make gen-command-docs build
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
